/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Column: typeof import('./src/components/table/column.vue')['default']
    Table: typeof import('./src/components/table/table.vue')['default']
  }
}
